#!/usr/bin/env bats

# @file tests/install/common/setup_git_hooks.bats
# @brief Test Git hook setup from a main checkout and linked worktree.
# @description
#   Builds a temporary repository, then verifies linked-worktree setup preserves
#   its shared prek shim and commits continue to invoke the hook.

readonly SCRIPT_PATH="${BATS_TEST_DIRNAME}/../../../scripts/setup_git_hooks.sh"

@test "[common] setup_git_hooks preserves and reuses the shared prek hook in a linked worktree" {
    local repo_root="${BATS_TEST_TMPDIR}/repo"
    local linked_root="${BATS_TEST_TMPDIR}/linked"
    local stub_bin="${BATS_TEST_TMPDIR}/bin"
    local prek_calls="${BATS_TEST_TMPDIR}/prek-calls"
    local hook_runs="${BATS_TEST_TMPDIR}/hook-runs"
    local hook_snapshot="${BATS_TEST_TMPDIR}/pre-commit.before"
    local other_hook_snapshot="${BATS_TEST_TMPDIR}/other-pre-commit.before"
    local hooks_dir
    local linked_hooks_dir

    export GIT_CONFIG_GLOBAL="${BATS_TEST_TMPDIR}/global.gitconfig"
    export GIT_CONFIG_NOSYSTEM=1
    : > "${GIT_CONFIG_GLOBAL}"

    mkdir -p "${repo_root}" "${stub_bin}"
    git -C "${repo_root}" init -q
    git -C "${repo_root}" config user.name "Test User"
    git -C "${repo_root}" config user.email "test@example.invalid"
    git -C "${repo_root}" config core.hooksPath "$(git -C "${repo_root}" rev-parse --absolute-git-dir)/hooks"
    printf 'initial\n' > "${repo_root}/tracked.txt"
    git -C "${repo_root}" add tracked.txt
    git -C "${repo_root}" commit -m "Initial commit"

    cat > "${stub_bin}/prek" << 'EOF'
#!/usr/bin/env bash
set -Eeuo pipefail

printf '%s\n' "$*" >> "${PREK_CALLS}"

case "${1:-}" in
    install)
        hooks_dir="$(git rev-parse --git-path hooks)"
        mkdir -p "${hooks_dir}"
        cat > "${hooks_dir}/pre-commit" <<'HOOK'
#!/bin/sh
# File generated by prek: https://github.com/j178/prek
HERE="$(cd "$(dirname "$0")" && pwd)"
exec prek hook-impl --hook-dir "$HERE" --script-version 4 --hook-type=pre-commit -- "$@"
HOOK
        chmod +x "${hooks_dir}/pre-commit"
        ;;
    hook-impl)
        printf 'prek hook implementation ran\n' >> "${PREK_RUNS}"
        ;;
    *)
        exit 2
        ;;
esac
EOF
    chmod +x "${stub_bin}/prek"

    run bash -c 'cd "$1" && PATH="$2:$PATH" PREK_CALLS="$3" PREK_RUNS="$4" bash "$5"' \
        bash "${repo_root}" "${stub_bin}" "${prek_calls}" "${hook_runs}" "${SCRIPT_PATH}"
    [ "${status}" -eq 0 ]
    [ "$(cat "${prek_calls}")" = "install" ]

    hooks_dir="$(git -C "${repo_root}" rev-parse --git-path hooks)"
    if [[ "${hooks_dir}" != /* ]]; then
        hooks_dir="${repo_root}/${hooks_dir}"
    fi
    cp "${hooks_dir}/pre-commit" "${hook_snapshot}"
    git -C "${repo_root}" worktree add --quiet -b linked "${linked_root}"
    linked_hooks_dir="$(git -C "${linked_root}" rev-parse --git-path hooks)"
    if [[ "${linked_hooks_dir}" != /* ]]; then
        linked_hooks_dir="${linked_root}/${linked_hooks_dir}"
    fi
    [ "${linked_hooks_dir}" = "${hooks_dir}" ]

    run bash -c 'cd "$1" && PATH="$2:$PATH" PREK_CALLS="$3" PREK_RUNS="$4" bash "$5"' \
        bash "${linked_root}" "${stub_bin}" "${prek_calls}" "${hook_runs}" "${SCRIPT_PATH}"
    [ "${status}" -eq 0 ]
    [[ "${output}" == *"reusing the existing prek pre-commit hook"* ]]
    [ "$(cat "${prek_calls}")" = "install" ]
    cmp -s "${hook_snapshot}" "${hooks_dir}/pre-commit"

    printf 'linked worktree commit\n' > "${linked_root}/next.txt"
    git -C "${linked_root}" add next.txt
    run env PATH="${stub_bin}:${PATH}" PREK_CALLS="${prek_calls}" PREK_RUNS="${hook_runs}" \
        git -C "${linked_root}" commit -m "Commit from linked worktree"
    [ "${status}" -eq 0 ]
    [ "$(cat "${hook_runs}")" = "prek hook implementation ran" ]
    [ "$(grep -c '^install$' "${prek_calls}")" -eq 1 ]
    [ "$(grep -c '^hook-impl ' "${prek_calls}")" -eq 1 ]
    cmp -s "${hook_snapshot}" "${hooks_dir}/pre-commit"

    printf '#!/bin/sh\nexit 0\n' > "${hooks_dir}/pre-commit"
    chmod +x "${hooks_dir}/pre-commit"
    cp "${hooks_dir}/pre-commit" "${other_hook_snapshot}"
    run bash -c 'cd "$1" && PATH="$2:$PATH" PREK_CALLS="$3" PREK_RUNS="$4" bash "$5"' \
        bash "${linked_root}" "${stub_bin}" "${prek_calls}" "${hook_runs}" "${SCRIPT_PATH}"
    [ "${status}" -eq 1 ]
    [[ "${output}" == *"existing pre-commit hook would be changed"* ]]
    [ "$(grep -c '^install$' "${prek_calls}")" -eq 1 ]
    cmp -s "${other_hook_snapshot}" "${hooks_dir}/pre-commit"
}
