#!/usr/bin/env zsh

typeset -gU path fpath

path=(
    $path
    /usr/local/{,s}bin(N-/)
    ${HOME}/.local/bin(N-/)
    ${HOME}/.local/bin/common(N-/)
    ${HOME}/.local/bin/server(N-/)
)

fpath=(
    $fpath
    ${HOME}/.local/bin/common(N-/)
    ${HOME}/.local/bin/server(N-/)
)

eval "$(sheldon source)"
