#!/usr/bin/env zsh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# zshrc

source-safe() { if [ -f "$1" ]; then source "$1"; fi; }

#
# aliases
#

source-safe "${HOME}/.local/bin/client/alias.sh"

#
# prezto
#

source-safe "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

#
# secrets
#

source-safe "{HOME}/.secret.zsh"

#
# fzf
#

source-safe "${HOME}/.config/fzf/config.zsh"

#
# golang
#

source-safe "${HOME}/.local/bin/client/golang.sh"

#
# rust
#

source-safe "${HOME}/.local/bin/client/rust.sh"

#
# GPG
#

source-safe "${HOME}/.local/bin/common/gpg.sh"

#
# OS specific settings
#

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    source-safe "${HOME}/.local/bin/client/linux.sh"

elif [[ "$OSTYPE" == "darwin"* ]]; then
    source-safe "${HOME}/.local/bin/client/macos.sh"

else
    # Unknown
    :
fi

#
# for working
#

source-safe "${HOME%/}/.work.d/.workrc"

#
# Auto load some functions
#

autoload -Uz \
    dev \
    fgc \
    git-delete-merged-branches \
    chezmoi-cd \
    setup-python-env \
    connect-hosei-vpn \
    disconnect-vpn

# To customize prompt, run `p10k configure` or edit ~/.config/powerlevel10k/p10k.zsh
[[ ! -f ~/.config/powerlevel10k/p10k.zsh ]] || source ~/.config/powerlevel10k/p10k.zsh
