#!/usr/bin/env zsh

#
# Path settings
#
typeset -gU path fpath
path=(
    $path
    /usr/local/{,s}bin(N-/)
    ${HOME}/.local/bin(N-/)
    ${HOME}/.local/bin/common(N-/)
)
fpath=(
    $fpath
    ${HOME}/.local/bin/common(N-/)
)

#
# sheldon initialization
#
eval "$(sheldon source)"
