#!/usr/bin/env zsh

_zshenv_private="${HOME}/.zshenv_private"
_zshenv_mise="${HOME}/.config/shell/mise.zsh"

if [ -f "${_zshenv_private}" ]; then
    source "${_zshenv_private}"
fi

if [ -f "${_zshenv_mise}" ]; then
    source "${_zshenv_mise}"
fi

unset _zshenv_mise _zshenv_private
