[".local/bin/nvinfo"]
    type = "file"
    url = "https://github.com/shunk031/nvinfo-go/releases/latest/download/nvinfo_linux_x86_64.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/nvinfo".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "nvinfo"]

[".local/bin/autocvd"]
    type = "file"
    url = "https://github.com/shunk031/autocvd-go/releases/latest/download/autocvd_linux_x86_64.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/autocvd".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "autocvd"]

[".local/bin/age"]
    type = "file"
    url = "https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-linux-amd64.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/age".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "age"]

[".local/bin/exa"]
    type = "archive"
    url = "https://github.com/ogham/exa/releases/download/v0.10.1/exa-linux-x86_64-v0.10.1.zip"
    executable = true
    extract = true
    stripComponents = 1
    indluce = ["bin/exa"]
    refreshPeriod = "168h"
