#!/usr/bin/env bash

# for mise shims
# shellcheck source=../../dot_config/exact_shell/mise.bash
if [ -f "${HOME%/}/.config/shell/mise.bash" ]; then
    source "${HOME%/}/.config/shell/mise.bash"
fi

if [ "$TERM" = "dumb" ]; then
    echo -n
else
    command -v zsh > /dev/null && exec zsh
fi
