# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[plugins.custom-commands]
inline = 'autoload -Uz dev'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
apply = ['defer']

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'
apply = ['defer']

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ['defer']

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.alias]
local = '~/.local/bin/server'
use = ['aliases.sh']
apply = ['source']

[plugins.fzf]
local = '~/.config/fzf'
use = ['config.zsh']
apply = ['defer']

[plugins.pyenv]
local = '~/.local/bin/server'
use = ['pyenv.sh']
apply = ['defer']

[plugins.cuda]
local = '~/.local/bin/server'
use = ['cuda.sh']
apply = ['source']

[plugins.ssh-agent]
local = "~/.local/bin/server"
use = ['ssh_agent.sh']
apply = ['source']

[plugins.gpg]
local = '~/.local/bin/common'
use = ['gpg.sh']
apply = ['source']

[plugins.history]
local = '~/.local/bin/server'
use = ['history.zsh']
apply = ['source']
