[tools]
go = "latest"
node = "lts"
rust = "latest"
python = "3.11"

age = "latest"
aws-cli = "latest"
bats = "latest"
bun = "latest"
chezmoi = "latest"
dotenvx = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
gcloud = "latest"
hugo-extended = "0.136.5"
jq = "latest"
kubectx = "latest"
shellcheck = "latest"
shfmt = "latest"
uv = "latest"
yazi = "latest"
yq = "latest"

"aqua:google-antigravity/antigravity-cli" = "latest"

"cargo:pueue" = "latest"

"github:cli/cli" = "latest"
"github:d-kuro/gwq" = "latest"
"github:shuntaka9576/blocc" = { version = "latest", os = ["linux"] }
"github:x-motemen/ghq" = "latest"

"npm:@anthropic-ai/claude-code" = "latest"
"npm:bash-language-server" = "latest"
"npm:fast-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:pyright" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
