#!/usr/bin/env bash

# @file scripts/setup_git_hooks.sh
# @brief Install the repository's Git hooks without replacing a shared hook from a linked worktree.
# @description
#   The main checkout keeps the normal `prek install` behavior. A linked worktree
#   reuses an existing `prek` pre-commit shim and refuses to replace another hook.

set -Eeuo pipefail

git_dir="$(git rev-parse --absolute-git-dir)"
common_dir="$(git rev-parse --git-common-dir)"

if [[ "${common_dir}" != /* ]]; then
    common_dir="$(git rev-parse --show-toplevel)/${common_dir}"
fi

git_dir="$(cd "${git_dir}" && pwd -P)"
common_dir="$(cd "${common_dir}" && pwd -P)"

if [[ "${git_dir}" == "${common_dir}" ]]; then
    exec prek install
fi

hooks_dir="$(git rev-parse --git-path hooks)"
if [[ -z "${hooks_dir}" ]]; then
    hooks_dir="${common_dir}/hooks"
elif [[ "${hooks_dir}" != /* ]]; then
    hooks_dir="$(git rev-parse --show-toplevel)/${hooks_dir}"
fi

pre_commit_hook="${hooks_dir}/pre-commit"
if [[ -e "${pre_commit_hook}" || -L "${pre_commit_hook}" ]]; then
    if grep -Fq '# File generated by prek:' "${pre_commit_hook}"; then
        printf 'Linked worktree is reusing the existing prek pre-commit hook; leaving it unchanged.\n'
        exit 0
    fi

    printf 'Cannot install prek from a linked worktree because an existing pre-commit hook would be changed.\n' >&2
    printf 'The hook was left unchanged. Run make setup from the main checkout first.\n' >&2
    exit 1
fi

exec prek install
