[".pyenv"]
    type = "git-repo"
    url = "https://github.com/pyenv/pyenv.git"
    refreshPeriod = "168h"

[".pyenv/plugins/pyenv-pyenv-virtualenv"]
    type = "git-repo"
    url = "https://github.com/pyenv/pyenv-virtualenv"
    refreshPeriod = "168h"
