name: Snippet install
on:
  push:
    branches: [master]
  schedule:
    - cron: "0 0 * * 5"

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup dotfiles with snippet
        run: bash -cex "$(curl -LsS http://shunk031.me/dotfiles/setup.sh) --yes"
