name: Snippet install

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
        system: [client, server]
        exclude:
          - os: macos-14
            system: server

    runs-on: ${{ matrix.os }}
    env:
      # DOTFILES_DEBUG: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Set up SSH agent and add the private deploy key for the private dotfiles repo
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_DOTFILES_PRIVATE_DEPLOY_KEY }}

      - name: Setup dotfiles with snippet
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          OS: ${{ matrix.os }}
          SYSTEM: ${{ matrix.system }}
        run: |
          if [ "${OS}" == "macos-14" ]; then
            printf "${EMAIL_ADDRESS}\n" | bash -c "$(curl -fsLS https://shunk031.me/dotfiles/setup.sh)"
            #              │
            #              └─ Simulate inputting an email address into the chezmoi's config.

          elif [ "${OS}" == "ubuntu-latest" ]; then
            printf "${EMAIL_ADDRESS}\n${SYSTEM}\n" | bash -c "$(wget -qO - https://shunk031.me/dotfiles/setup.sh)"
            #              │               │
            #              │               └─ Simulate inputting an system arcitecture into the config.
            #              └─ Simulate inputting an email address into the config.

          else
            echo "${OS} is not supported" >&2
            exit 1
          fi
